version: '3.7'
services:
  quarkus-hello:
    image: beyonder/quarkus-hello:1.0.0-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - QUARKUS_DATASOURCE_USERNAME=fajri
      - QUARKUS_DATASOURCE_PASSWORD=12345678
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/quarkusdb
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fajri
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=quarkusdb
